# 第八章：异常处理

- ## 异常的定义

  - **概述：**

    - **运行期间出现的错误，而不是编译时的语法错误**
      例如，
      打开一个不存在的文件
      网络连接中断
      操作数组越界等

  - **异常的继承树**

    - `Throwable`类是java语言中的所有错误和异常的基类
      - Error(错误)：特指应用程序在运行期间发生的严重错误，异常处理机制不做处理
      - Exception(异常)：
        - RuntimerException（运行时异常，非检查性异常）：代码编译过程中不会自动监测的异常，运行时才发生的异常，不需要处理该类异常
        - Check Exception(检查性异常 IOException)--先知:代码编译过程中会自动检查该代码是否会出现异常，一定要写出响应的代码处理异常，否者编译不通过

  - **处理异常的两种方式：**

    - 自行处理(在哪里出现的异常就在哪里处理)：try{可能出现的异常}catch(异常的类型){异常处理代码}

      - 可能引发异常的语句封入在 try 块内，而处理异常的相应语句则封入在 catch 块内。

        ```java
        /**
        	 *  try{}catch(){}
        	 *  ①是用来捕获并处理try块抛出的异常的代码块。没有try块，catch块不能单独存在
        	 *  ②可以有多个catch块，以捕获不同类型的异常
        	 * 
        	 *执行过程：每次try块有异常抛出，系统会试着从上到下往每个catch块中传参，直到遇到一个类型匹配的catch块为止
        	 *	 
        	 *
        	 * 注意：
        	 * 	①如果有多个catch只会匹配第一个出现异常的catch语句块,后面的catch不再执行
        	 * 	②如果try语句块中的代码出现了异常那么执行相对应的catch语句块，try语句块中出行异常的下一行代码不再执行
        	 * 	③catch块中的形参为Exception类型需要放到最后，也可以只用一个catch语句块但他的类型为Excpetion(不建议)，出现什么异常就处理什么异常类型
        	 * 	④catch中类型声明的顺序：如果抛出的异常有父子关系时先catch子类异常再catch父类异常
        	 */
        	public static void getCheckException(){
        		File file=new File("D:/x.txt");
        		try {
        			FileInputStream in=new FileInputStream(file);
        			System.out.println("zhangsan-------------------");
        			Class.forName("student");//将类加载进内存
        			
        		}/*catch(ClassNotFoundException e){
        //			System.out.println("类找不到哦");
        			e.printStackTrace();//打印堆栈异常信息  包括错误的信息和错误代码在第几行
        		} catch (FileNotFoundException e) {
        //			System.out.println("文件找不到哦");
        			e.printStackTrace();
        		}*/catch(Exception e) {
        //			System.out.println("异常");
        			e.printStackTrace();
        		}
        	}
        	
        	public static void main(String[] args) {
        		getCheckException();
        	}
        
        ```

        - **finally语句块**

          ```java
          public class TestException2 {
          
          //	finally语句块
          	/**
          	 * 
          	 * finally:最终执行--在try catch执行完之后无论如何都会执行的语句块
          	 * 		语法： try{}finally{}    try{} catch(){}fianlly{}
          	 * 
          	 * 作用：一般用于释放资源
          	 * @param args
          	 */
          	public static void testFinally() {
          		File file=new File("D:/x.txt");
          		try {
          			FileInputStream in=new FileInputStream(file);
          			System.out.println("try语句块----------------");
          			Class.forName("student");
          			System.out.println("student---------------");
          		} catch (FileNotFoundException e) {
          //			e.printStackTrace();
          			System.out.println("catch语句块文件找不到");
          		} catch (ClassNotFoundException e) {
          //			e.printStackTrace();
          			System.out.println("catch语句块类找不到哦");
          		}finally {
          			System.out.println("这是finlly语句块-------------");
          		}
          	}
          	public  static void testFinally2() {
          		try {
          			System.out.println("try");
          		}finally {
          			System.out.println("finally");
          		}
          	}
          	
          	public static void testFinally3() {
          		int i=10;
          		try {
          			i++;
          			Class.forName("student");
          		} catch (Exception e) {
          			i++;
          			e.printStackTrace();
          		}finally {
          			System.out.println("fianlly"+i);
          		}
          		System.out.println("try-catch之后的代码");
          	}
          	public static int testFinally4() {
          		int i=10;
          		try {
          			i++;
          			
          			Class.forName("student");
          			 /*
          			  * 如果try中有return语句,执行到return后先将返回值保存到return中，然后再看有没有finally语句块
          			  * 有，有finally语句块如果fianlly中没有return那么执行finally语句块然后再执行try中的return
          			  * 
          			  *  如果fianlly中有return那么执行finaly中的return语句，之前的try中的return失效
          			  */
          			return i;
          		} catch (Exception e) {
          			i++;
          			return i;
          //			e.printStackTrace();
          		}finally {
          			i++;
          			System.out.println("fianlly"+i);
          			return i;
          		}
          //		System.out.println("try-catch之后的代码");
          //		return i;
          	}
          	
          	public static void main(String[] args) {
          //		getCheckException();
          //		testFinally();
          //		testFinally2();
          		System.out.println(testFinally4());
          	}
          
          }
          ```

          

    - **回避异常(将异常抛给下一个调用者)**：throws

      - 在方法声明中包含 throws 子句，通知潜在调用者，如果发生了异常，必须由调用者处理

      ```java
      public class TestException3 {
      	/**
      	 * throws:作用在方法上，告诉下一个调用者需要处理的异常类型
      	 * throws 异常类型
      	 *   throws 后面能跟多个异常，中间用逗号隔开
      	 * @throws IOException
      	 * @throws ClassNotFoundException 
      	 * 
      	 * throw:作用在方法内，抛出明确的异常
      	 *  语法：
      	 *  	throw new Throwable类型(包括子类)
      	 * 注意：throw需要和try catch或者thows结合一起使用
      	 */
      	public static void getResult() throws IOException, ClassNotFoundException {
      		File f=new File("D:/a.txt");
      		f.createNewFile();
      		Class.forName("student");
      	}
      	
      	public static void testThrow(int i,int b) throws ClassNotFoundException {
      		if(i!=b) {
      			throw new ClassNotFoundException();//明确抛出异常类型
      		}
      	}
      	
      	public static void getName() throws IOException, ClassNotFoundException {
      			getResult();
      	}
      
      	public static void main(String[] args) {
      		/*try {
      			getName();
      		} catch (IOException e) {
      			e.printStackTrace();
      		} catch (ClassNotFoundException e) {
      			e.printStackTrace();
      		}*/
      		try {
      			testThrow(2,2);
      		} catch (ClassNotFoundException e) {
      			System.out.println("两个值不相等");
      		}
      	}
      
      }
      ```

      

      - **自定义异常**

        - 自定义异常一定要继承Exception
        - 使用throw抛出自定义异常
- 为什么使用自定义异常？
          - 当程序中的异常没有在java异常API中定义时，可以自定义异常
        
        

